# Main parameters
root_dir: '../pytorch-CycleGAN-and-pix2pix/datasets/horse2zebra'

# Architecre Parameters

generator_params:
  equivariance: 'p4m'
  block_expansion: 22
  num_down_blocks: 2
  num_bottleneck_blocks: 6
  max_features: 91
  pool: 'avg'
  upsample: 'nearest'
  sn: False
  group_pool: 'avg'
  bn: 'instance'
  scales: 1

discriminator_params:
  equivariance: 'p4m'
  scales: 1
  block_expansion: 22
  num_blocks: 4
  max_features: 182
  pool: 'avg'
  sn: False
  bn: 'instance',
  group_pool: 'avg'

# Train parameters
num_epochs: 200

lr_generator: 1.0e-4
lr_discriminator: 4.0e-4
bs: 20

identity_loss_weight: 10
cycle_loss_weight: 0
adversarial_loss_weight: 1

