# Main parameters
root_dir: '../pytorch-CycleGAN-and-pix2pix/datasets/cityscapes'
load_size: 146
crop_size: 128
# Architecre Parameters

generator_params:
  equivariance: 'p4m'
  block_expansion: 22
  num_down_blocks: 2
  num_bottleneck_blocks: 6
  pool: 'avg'
  upsample: 'nearest'
  sn: False
  group_pool: 'linear'
  bn: 'instance'
  scales: 1

discriminator_params:
  equivariance: null
  scales: 1
  block_expansion: 64
  num_blocks: 4
  pool: 'avg'
  sn: True
  bn: null
  group_pool: 'identity'

transform_params:
  sigma_affine: 0.1
  sigma_tps: 0.005
  points_tps: 5
  flips: True


gan_loss_type: 'lsgan'
# Train parameters
num_epochs: 200
lr_generator: 2.0e-4
lr_discriminator: 2.0e-4
bs: 4

identity_loss_weight: 5
cycle_loss_weight: 0
adversarial_loss_weight: 1
equivariance_loss_weight_generator: 0
equivariance_loss_weight_discriminator: 0
